CREATE TABLE IF NOT EXISTS events (
    id VARCHAR(21) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    start TIMESTAMP WITH TIME ZONE NOT NULL,
    end TIMESTAMP WITH TIME ZONE,
    all_day BOOLEAN DEFAULT FALSE,
    extended_props JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);